
analysis:
    nname: ['de10gf', 'de10bf', 'eur50bf', 'de50gf', 'de50bf']
    method: ['ptpf', 'ptpf-adj']
    power: ['net']


line_volume_limit: 1.2
adjust_shadowprices: false


# =============================================================================
# copied from pypsa-eur config
# =============================================================================

costs:
  emission_prices: # only used with the option Ep
    co2: 130. # This must be the same as in the other config files!

solving:
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-6
    FeasibilityTol: 1.e-7
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
